Add SPM support
GlobalRadio/StreamingKit pull request #24
Opened 2023-03-22 14:53 UTC by igor-kokoev-global

# Description
* Added Package.swift
* Created symlinks for files

2023-04-24 12:27 UTC, iamszabo approved these changes

2023-04-24 12:28 UTC, iamszabo requested changes
Should we bump the version number?

2023-04-24 12:31 UTC, igor-kokoev-global commented
> Should we bump the version number?

I'm not sure if we need to. We don't change any source files

Do you think we should?

2023-05-22 07:35 UTC, iamszabo approved these changes

2023-05-22 11:18 UTC, merged